name: CI/CD

on:
  push:
    branches:
      - main # Change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.200" # Change this to match your .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish Artifact
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ActiVeTech1 # Change this to your Azure App Service name
          publish-profile: ${{ secrets.AZURE_ACTIVETECH1_PUBLISH_PROFILE}}
